FROM python:latest

# Install random Python packages globally
RUN pip install --no-cache-dir cowsay
RUN pip install --no-cache-dir httpie
RUN pip install --no-cache-dir speedtest-cli
RUN pip install --no-cache-dir glances
RUN pip install --no-cache-dir rich-cli
RUN pip install --no-cache-dir yq
RUN pip install --no-cache-dir visidata
RUN pip install --no-cache-dir youtube-dl

